### ISSUE TITLE
reference link disable in your README.md

### ISSUE THREAD

**Issue by HFourier** [elchead/k8s-migration-controller#1]
When I try to ccess link [https://astobbe.me/posts/k8s-monitoring-with-influx-telegraf/](https://astobbe.me/posts/k8s-monitoring-with-influx-telegraf/) in your README.md,  I find that the url is disable. I am trying to realize this, can you find similar website？

**Comment by elchead** [comment]
here is the updated link: https://blog.adrianstobbe.com/tutorial-k8s-monitoring-with-influxdbs-telegraf
thanks for sharing!

**Comment by HFourier** [comment]
> here is the updated link: https://blog.adrianstobbe.com/tutorial-k8s-monitoring-with-influxdbs-telegraf thanks for sharing!

OK, thanks a lot, I will try.

**Comment by HFourier** [comment]
Another question, when I try deploy Influxdb2 by `helm upgrade --install influx2 influxdata/influxdb2`, the pod is pending and an error happened: 
>   0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for schedule. 

How can I fix it, does the PVC is necessary ?

**Comment by elchead** [comment]
> Another question, when I try deploy Influxdb2 by `helm upgrade --install influx2 influxdata/influxdb2`, the pod is pending and an error happened:
> 
> > 0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for schedule.
> 
> How can I fix it, does the PVC is necessary ?

You need to create a Persistent Volume such that the PVC can be bound. The cluster needs to have either [dynamic provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) or you have to create it manually.
For an easy setup, I recommend you to use the managed InfluxDB service. Then you just need to connect the telegraf to the service and don't need a PV.
